package org.project.backend.exception.enumeration;

public enum ExceptionType {
    EMAIL_ALREADY_EXISTS,
    WRONG_CREDENTIALS,
    USER_NOT_FOUND,
    RULE_FILE_NOT_FOUND,
    FAILED_TO_MOVE_FILE,
    FAILED_TO_CREATE_JOB,
    FAILED_TO_EXECUTE_JOB,
    FAILED_TO_DELETE_JOB,
    FAILED_TO_UPLOAD_FILE,
    FAILED_TO_CHECK_JOB_STATUS,
    FAILED_TO_READ_FILE,
}
